name: coruja
description: A nodeJS express like library. Provides facilities to configure routes to HTTP requests of type GET/POST and ways to change the default request object received by the route function handler.
version: 0.0.1
homepage: https://github.com/dfeprado/coruja4dart

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
